### ISSUE TITLE
Report chart not Displaying in the GUI window

### ISSUE THREAD

**Issue by Adarshs169** [prashantsengar/TimeTracker#5]
The reports generated should be displayed on the GUI window rather on the console window.

**Comment by prashantsengar** [comment]
@Adarshs169, can you share a screenshot of what do you mean by report is displayed in the console window. As much as I have tested, it creates a new GUI window for the report

**Comment by Adarshs169** [comment]
The report is shown in a separate window. But as a standard application , it should show on the GUI window. The matplotlib library don't display result at GUI unless u have coded it for that

**Comment by Adarshs169** [comment]
![s2](https://user-images.githubusercontent.com/32703713/70375291-09aaea80-1922-11ea-80d7-3d169e120696.jpeg)

**Comment by prashantsengar** [comment]
@Adarshs169, I had expected it to work that way only :)

**Comment by prashantsengar** [comment]
Fixed by @suchintan-p
